const GET_TEAM_DATA = 'GET_TEAM_DATA'
const ADD_MEMBER = 'ADD_MEMBER'
const CREATE_TODO = 'CREATE_TODO'
const EDIT_TODO = 'EDIT_TODO'
const EDIT_COMPLETE = 'EDIT_COMPLETE'
const DELETE_TODO = 'DELETE_TODO'
const DELETE_TODOS = 'DELETE_TODOS'
const TOGGLE_TODO = 'TOGGLE_TODO'
const PRIORITY_TODO = 'PRIORITY_TODO'
const CHANGE_FILTER = 'CHANGE_FILTER'
const CANCLE_EDIT = 'CANCLE_EDIT'

export {
  GET_TEAM_DATA,
  ADD_MEMBER,
  CREATE_TODO,
  DELETE_TODO,
  DELETE_TODOS,
  TOGGLE_TODO,
  PRIORITY_TODO,
  CHANGE_FILTER,
  EDIT_TODO,
  CANCLE_EDIT,
  EDIT_COMPLETE,
}
