const PRIORITY = ['NONE', 'FIRST', 'SECOND'];
PRIORITY['NONE'] = 0;
PRIORITY['FIRST'] = 2;
PRIORITY['SECOND'] = 1;

const SHOW = {
  ALL: 'ALL',
  PRIORITY: 'PRIORITY',
  ACTIVE: 'ACTIVE',
  COMPLETED: 'COMPLETED',
};

export { PRIORITY, SHOW };
